version: "3"
services:
  db:
    image: postgres:15-alpine@sha256:fa484d844b88ac34811daf3da66af1fd17e34b0e1ff5d1b6f904269c85890dc0
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_PASSWORD: ${PG_USR_PWD}
      POSTGRES_USER: ${PG_USR_NAME}
    logging:
      driver: "none"
    volumes:
      - pg_vol:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2.5.30@sha256:1aae39563cf15d8cfc6371b6d33805653d9348a1af944a8be4501db36f120b84
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${PG_DB_NAME}
      DB_USER: ${PG_USR_NAME}
      DB_PASS: ${PG_USR_PWD}
    ports:
      - "3000:3000"
    depends_on:
      - db

  exporter:
    build: ../
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${PG_DB_NAME}
      DB_USER: ${PG_USR_NAME}
      DB_PASS: ${PG_USR_PWD}
    volumes:
      - ./output:/app/output
    depends_on:
      - wiki

volumes:
  pg_vol: